
```{r load_packages}
packages <- c("dplyr", "lubridate", "stringi", "stringdist", "ggplot2", "tidyr")
for (package in packages) {
    library(package, character.only = TRUE, warn.conflicts = FALSE)
}
```

```{r load_data}
original_data_url <- "https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2FStormData.csv.bz2"
original_data_bz2 <- "StormData.csv.bz2"
if (!file.exists(original_data_bz2)) {
    download.file(original_data_url, original_data_bz2, method = "curl")
    download_date <- Sys.time()
} else {
    download_date <- file.info(original_data_bz2)[, "ctime"]
}
original_data <- read.csv(original_data_bz2, stringsAsFactors = FALSE,
                          nrow = 10000)
```

```{r tidy_data}
event_types <- c("Astronomical Low Tide", "Avalanche", "Blizzard",
    "Coastal Flood", "Cold/Wind Chill", "Debris Flow", "Dense Fog",
    "Dense Smoke", "Drought", "Dust Devil", "Dust Storm", "Excessive Heat",
    "Extreme Cold/Wind Chill", "Flash Flood", "Flood", "Frost/Freeze",
    "Funnel Cloud", "Freezing Fog", "Hail", "Heat", "Heavy Rain", "Heavy Snow",
    "High Surf", "High Wind", "Hurricane (Typhoon)", "Ice Storm", 
    "Lake-Effect Snow", "Lakeshore Flood", "Lightning", "Marine Hail",
    "Marine High Wind", "Marine Strong Wind", "Marine Thunderstorm Wind",
    "Rip Current", "Seiche", "Sleet", "Storm Surge/Tide", "Strong Wind",
    "Thunderstorm Wind", "Tornado", "Tropical Depression", "Tropical Storm",
    "Tsunami", "Volcanic Ash", "Waterspout", "Wildfire", "Winter Storm",
    "Winter Weather")

normalize_event_type <- Vectorize(function(event_type) {
    event_type <- event_type %>%
        # If alternatives are given, take the first one:
        stri_extract_first_regex("^[^/]+") %>%
        # Trim whitespaces:
        stri_trim_both() %>%
        # Handle some conflictive cases:
        stri_replace_first_fixed("TSTM", "Thunderstorm") %>%
        stri_replace_first_regex("^COLD$", "Cold/Wind Chill") %>%
        stri_replace_first_regex("^EXTREME COLD$", "Extreme Cold/Wind Chill") %>%
        stri_replace_first_regex("^WIND$", "Strong Wind") %>%
        # Convert to 'Title Case'
        stri_trans_totitle()
    distances <- stringdist(event_type, event_types, method = "lv")
    event_types[which.min(distances)]
})

numeric_exp <- function(letter) {
    recognized_exp <- c(`1` = 1, `2` = 2, H = 2, h = 2, `3` = 3, 
        K = 3, k = 3, `4` = 4, `5` = 5, `6` = 6, M = 6, m = 6,
        `7` = 7, `8` = 8, `9` = 9, B = 9, b = 9)
    letter[!letter %in% names(recognized_exp)] <- ""
    sapply(letter, function(l) do.call(switch, c(list(l), recognized_exp, 0)))
}

tidy_data <- original_data %>%
    # Select a subset of the columns:
    select(BGN_DATE, EVTYPE, FATALITIES, INJURIES, 
           PROPDMG, PROPDMGEXP, CROPDMG, CROPDMGEXP) %>%
    # Filter events with nonzero values in at least one of the columns
    # FATALITIES, INJURIES, PROPDMG or CROPDMG:
    filter(FATALITIES > 0 | INJURIES > 0 | PROPDMG > 0 | CROPDMG > 0) %>%
    # Convert BGN_DATE to a vector of class POSIXct:
    mutate(BGN_DATE = mdy_hms(BGN_DATE)) %>%
    # Normalize EVTYPE:
    mutate(EVTYPE = factor(normalize_event_type(EVTYPE))) %>%
    # Compute the numerical values of PROPDMG and CROPDMG:
    mutate(PROPDMG = PROPDMG * 10^numeric_exp(PROPDMGEXP)) %>%
    mutate(CROPDMG = CROPDMG * 10^numeric_exp(CROPDMGEXP)) %>%
    select(-PROPDMGEXP, -CROPDMGEXP)

colnames(tidy_data) <- c("date", "event_type", "fatalities", "injuries",
                         "property_damage", "crop_damage")
```

```{r events}
ggplot(tidy_data, aes(x = date)) +
    geom_bar(binwidth = as.numeric(duration(1, "year"))) +
    labs(title = "NOAA Storm Database", x = "Date", 
         y = "Number of recorded events")
```

```{r population_data}
population_data <- tidy_data %>%
    group_by(event_type) %>%
    summarize(Fatalities = sum(fatalities), Injuries = sum(injuries)) %>%
    gather(damage_type, damage_count, -event_type) %>%
    group_by(damage_type) %>%
    arrange(desc(damage_count)) %>%
    filter(row_number() <= 5)

ggplot(population_data, aes(x = reorder(event_type, -damage_count),
                            y = damage_count, fill = event_type)) +
    geom_bar(stat = "identity") +
    facet_wrap(~ damage_type, scales = "free_x") +
    theme(legend.position = "none",
          axis.text.x = element_text(angle = 45, hjust = 1)) +
    labs(title = "Damages to Population Health", x = NULL, y = "Total")
```

```{r economy_data}
economy_data <- tidy_data %>%
    group_by(event_type) %>%
    summarize(total_damages = sum(property_damage) + sum(crop_damage)) %>%
    arrange(desc(total_damages)) %>%
    filter(row_number() <= 10)

ggplot(economy_data, aes(x = reorder(event_type, -total_damages), 
                         y = total_damages / 10^9, fill = event_type)) +
    geom_bar(stat = "identity") +
    theme(legend.position = "none",
          axis.text.x = element_text(angle = 45, hjust = 1)) +
    labs(title = "Damages to the Economy", x = NULL, y = "Cost (billion dollars)")
```
